### ISSUE TITLE
Problem in .as_cv when using an ECMS object that is created by adding ECMS object + EC object

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#20]
I tried to find a workaround to using the noisy EC data in Zilien dataset by doing something like the following:
zilien_obj = Measurement.read( "example_data", reader="zilien")
bio_obj =  Measurement.read( "example_ec data", reader="biologic")
combi_obj = zilien_obj + bio_obj

This results in an ECMS object, where I can select the less noisy "<I>/mA" as J_str to get a plot vs time:combi_obj.plot_measurement(J_str="<I>/mA" ) 

However, when trying to first convert to cv with combi_obj.as_cv() and then using combi_obj.plot_vs_potential() something breaks.
(1) initially the cycles are NoneType objects
(1) When using redefine_cycle, the cycles are somehow broken into very small fragments (in the case I tested 3 cycles became 10)
(2) combi_obj.plot_vs_potential(J_str="<I>/mA") gives following error: AttributeError: 'Line2D' object has no property 'j_str'

**Comment by spoeka22** [comment]
this might be related to issue #14

**Comment by ScottSoren** [comment]
I think #14  is a much worse headache... it's been solved in a big restructuring on the [master] branch. Merging that into [user_ready] will be tough.

**Comment by spoeka22** [comment]
See comment to #17. Problem solved by not introducing the conflict of having to deal with concurrent EC data from different sources (biologic file and zilien file)

**Comment by spoeka22** [comment]
I'm reopening this issue, because I realised the problem also occurs when just combining several biologic files (a CVA and some CP measurements), so it's not only because of incompatibility with EC data from different importers.

**Comment by ScottSoren** [comment]
This is addressed in #30 . I'm assigning @KennethNielsen because as far as I can tell #30 is still on his desk :) 

As input to that, @spoeka22 , if you have time on your hands, it would be great to hear if the problem raised in this issue is solved if you [run ixdat from](https://ixdat.readthedocs.io/en/latest/developing.html) the [backend_fixes branch](https://github.com/ixdat/ixdat/tree/backend_fixes).

**Comment by AnnaWiniwarter** [comment]
Hej Soren, no unfortunately it still doesnt work. It breaks completely differently now, though:
If I import the zilien file as `MSMeasurement` and then try to add the `ECMeasurement` objects, I get following error:
```
  File "\ixdat\src\ixdat\techniques\ec_ms.py", line 70, in as_dict
    if self.calibration:

AttributeError: 'ECMSMeasurement' object has no attribute 'calibration'
```
if I just try to add two `ECMeasurement` objects, adding them works, but then if I convert them to a `CyclicVoltammogram` object with `.as_cv()`, I still can't choose cycles (note I tried to convert a CV+CP file together to CVs).

```
cvs[1]
Traceback (most recent call last):

  File "C:\Users\ANNAWI~1\AppData\Local\Temp/ipykernel_21872/3670235597.py", line 1, in <module>
    cvs[1]

  File "\ixdat\src\ixdat\measurements.py", line 583, in __getitem__
    series = self.get_series(key)

  File "\ixdat\src\ixdat\measurements.py", line 644, in get_series
    if key.endswith("-t") or key.endswith("-x"):

AttributeError: 'int' object has no attribute 'endswith'
```
@KennethNielsen I can provide a code example offline if you need

**Comment by ScottSoren** [comment]
@AnnaWiniwarter , is this okay to close after #50 ?
